<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName($nom)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Product p WHERE p.name like :nom ORDER BY p.name ASC"
            )
            ->setParameter('nom', $nom.'%')
            ->getResult();
    }

}
